import {Col, Container, Row} from "react-bootstrap";

export function Footer () {
    return (
            <>
                <Container>
                    <Row className="text-center mt-5 misc-text about-link">
                        <a href="/about" className="misc-text">About Gloomsmith Project</a>
                    </Row>
                    <Row className="mt-2 disclaimer">
                            DISCLAIMER: The quotes generated on this website are intended for entertainment purposes only. Any quotes attributed to real-life individuals or well-known personalities are fictional and not representative of their actual words or beliefs. The quotes are generated by artificial intelligence and should not be taken seriously. We do not endorse or claim any association with the individuals mentioned in the quotes. Users are solely responsible for their use of the generated quotes and should exercise discretion when sharing them.
                    </Row>

                </Container>
    </>
    )
}